import { chmod, lstat, mkdir, readFile, realpath, rename, unlink, writeFile } from "node:fs/promises";
import { basename, isAbsolute, relative, resolve } from "node:path";
import { randomUUID } from "node:crypto";

export const MAX_TOOL_BYTES = 1024;
export const MAX_DETAILS_BYTES = 8192; // ponytail: bounded detail; raise only with pagination.
const TYPES = new Set(["feature", "design-decision", "fix", "incident", "learning", "milestone"]);
const MARKER = ".dev-journal-recovery.json", VERSION = 1, PRIVATE = 0o600, DIR_PRIVATE = 0o700;
const slugify = (s: string) => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const skillify = (s: string) => s.toLowerCase().trim().replace(/[^a-z0-9.+]+/g, "-").replace(/^-|-$/g, "");
const text = (s: string, max = MAX_TOOL_BYTES) => Buffer.byteLength(s) <= max ? s : Buffer.from(s).subarray(0, Math.max(0, max - 16)).toString("utf8") + "\n[truncated]";
const safe = (s: unknown, max: number) => typeof s === "string" && s.trim().length > 0 && s.length <= max ? s.trim() : null;
const inline = (s: unknown, max: number) => { const value = safe(s, max); return value && !/[\p{Cc}]/u.test(value) ? value : null; };
const yaml = (s: string) => JSON.stringify(s);
const escapeRegex = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

type Fs = { mkdir: typeof mkdir; readFile: typeof readFile; writeFile: typeof writeFile; rename: typeof rename; unlink: typeof unlink; chmod: typeof chmod; realpath: typeof realpath; lstat: typeof lstat };
const disk: Fs = { mkdir, readFile, writeFile, rename, unlink, chmod, realpath, lstat };
type Snapshot = { ref: string; content: string | null; mode: number | null };
type Recovery = { version: number; root: string; project: string; entry: string; snapshots: Snapshot[] };

export type RecordInput = { approved: boolean; project: string; company: string; type: string; title: string; skills: string[]; impact: string; cv_ready: boolean; body: string; date?: string; related?: string };
export type JournalState = { commit: boolean; decided: boolean; nudged: boolean };
export const initialState = (): JournalState => ({ commit: false, decided: false, nudged: false });
export function parseState(data: unknown): JournalState { if (!data || typeof data !== "object") return initialState(); const value = data as Record<string, unknown>; return typeof value.commit === "boolean" && typeof value.decided === "boolean" && typeof value.nudged === "boolean" ? { commit: value.commit, decided: value.decided, nudged: value.nudged } : initialState(); }
export function isRecordResult(event: unknown): boolean { if (!event || typeof event !== "object") return false; const value = event as { toolName?: unknown; input?: unknown }; return value.toolName === "dev_journal" && !!value.input && typeof value.input === "object" && (value.input as { action?: unknown }).action === "record"; }
export function nudgeState(state: JournalState): JournalState | null { return state.commit && !state.decided && !state.nudged ? { ...state, nudged: true } : null; }
export function projectFrom(cwd: string, explicit?: string): string | null { return explicit ? slugify(explicit) || null : slugify(basename(cwd)) || null; }
export function normalizeRecordInput(input: RecordInput): RecordInput { return { ...input, project: slugify(input.project), company: slugify(input.company), skills: input.skills.map(skillify) }; }
export function confined(root: string, ref: string): string | null { if (!ref || ref.includes("\0") || isAbsolute(ref) || ref.includes("\\") || ref === "index.md" || ref === "skills-inventory.md") return null; const out = resolve(root, ref), rel = relative(root, out); return rel.startsWith("..") || rel === "" || !/^[-a-z0-9]+\/\d{4}-\d{2}-\d{2}-[-a-z0-9]+\.md$/.test(ref) ? null : out; }
export function validate(input: RecordInput): string | null {
  const retry = (field: string, requirement: string) => `Invalid dev_journal record field '${field}': ${requirement}. Retry dev_journal with corrected '${field}' and the same approved record.`;
  if (!input.approved) return "Dev-journal record requires approved:true after user approves `Journal ini?`. Ask first, then retry the same record.";
  if (!TYPES.has(input.type)) return retry("type", `use one of: ${[...TYPES].join(", ")}`);
  if (!inline(input.project, 80) || !/^[a-z0-9-]+$/.test(input.project)) return retry("project", "provide a non-empty name up to 80 characters; names are normalized to lowercase kebab-case");
  if (!inline(input.company, 80) || !/^[a-z0-9-]+$/.test(input.company)) return retry("company", "provide a non-empty name up to 80 characters; names are normalized to lowercase kebab-case");
  if (!inline(input.title, 180)) return retry("title", "provide one non-empty line up to 180 characters");
  if (!inline(input.impact, 500)) return retry("impact", "provide one non-empty line up to 500 characters");
  if (!safe(input.body, 12000)) return retry("body", "provide non-empty text up to 12000 characters");
  if (!Array.isArray(input.skills) || input.skills.length > 16 || input.skills.some((x) => !inline(x, 80) || !/^[a-z0-9.+-]+$/.test(x))) return retry("skills", "provide at most 16 non-empty names up to 80 characters each; names are normalized to lowercase kebab-case while preserving '.' and '+'");
  if (input.related !== undefined && (!inline(input.related, 240) || !/^[a-z0-9/_-]+$/.test(input.related))) return retry("related", "use a lowercase journal reference containing only letters, digits, '/', '_', or '-'");
  return null;
}
export function entryFor(input: RecordInput): { ref: string; l2: string; l1: string } { const date = input.date && /^\d{4}-\d{2}-\d{2}$/.test(input.date) ? input.date : new Date().toISOString().slice(0, 10); const slug = slugify(input.title); if (!slug) throw new Error("Invalid title."); const ref = `${input.project}/${date}-${slug}.md`, tags = ["journal/entry", `type/${input.type}`, `project/${input.project}`, `company/${input.company}`, ...input.skills.map((x) => `skill/${x}`), ...(input.cv_ready ? ["cv-ready"] : [])]; const l2 = `---\ntype: ${input.type}\nproject: ${input.project}\ncompany: ${input.company}\ndate: ${date}\ntitle: ${yaml(input.title)}\nskills: [${input.skills.map(yaml).join(", ")}]\nimpact: ${yaml(input.impact)}\ncv_ready: ${input.cv_ready}\ntags: [${tags.map(yaml).join(", ")}]\n---\n\n${input.body}${input.related ? `\n\nRelated: [[${input.related}]]` : ""}\n`; return { ref, l2, l1: `${date} ${input.type} ${slug} {${input.skills.join(", ")}} — ${input.impact}` }; }
function enoent(error: unknown): boolean { return !!error && typeof error === "object" && (error as { code?: unknown }).code === "ENOENT"; }
function under(root: string, path: string): boolean { const rel = relative(root, path); return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel)); }
function refOK(ref: string): boolean { return ref === MARKER || ref === "index.md" || ref === "skills-inventory.md" || /^[-a-z0-9]+\/(?:index\.md|\d{4}-\d{2}-\d{2}-[-a-z0-9]+\.md)$/.test(ref); }
async function rootPath(root: string, fs: Fs): Promise<string> { try { await fs.lstat(root); } catch (error) { if (!enoent(error)) throw error; await fs.mkdir(root, { recursive: true, mode: DIR_PRIVATE }); } const canonical = await fs.realpath(root), info = await fs.lstat(canonical); if (info.isSymbolicLink() || !info.isDirectory()) throw new Error("Invalid journal root."); return canonical; }
async function target(root: string, ref: string, fs: Fs): Promise<string> { if (!refOK(ref)) throw new Error("Invalid journal entry reference."); const canonical = await rootPath(root, fs), parts = ref.split("/"); let parent = canonical; for (const part of parts.slice(0, -1)) { parent = resolve(parent, part); if (!under(canonical, parent)) throw new Error("Invalid journal entry reference."); try { const info = await fs.lstat(parent); if (info.isSymbolicLink() || !info.isDirectory()) throw new Error("Invalid journal write target."); } catch (error) { if (!enoent(error)) throw error; await fs.mkdir(parent, { mode: DIR_PRIVATE }); const info = await fs.lstat(parent); if (info.isSymbolicLink() || !info.isDirectory()) throw new Error("Invalid journal write target."); } const actual = await fs.realpath(parent); if (actual !== parent || !under(canonical, actual)) throw new Error("Invalid journal write target."); }
  const path = resolve(parent, parts.at(-1)!); if (!under(canonical, path)) throw new Error("Invalid journal entry reference."); try { if ((await fs.lstat(path)).isSymbolicLink()) throw new Error("Invalid journal write target."); } catch (error) { if (!enoent(error)) throw error; } return path; }
async function read(path: string, fs: Fs): Promise<string> { try { return await fs.readFile(path, "utf8"); } catch (error) { if (enoent(error)) return ""; throw error; } }
async function atomic(root: string, ref: string, value: string, mode: number | null, fs: Fs): Promise<void> { const path = await target(root, ref, fs), tmp = `${path}.dev-journal-${randomUUID()}`, fileMode = mode ?? PRIVATE; await fs.writeFile(tmp, value, { encoding: "utf8", mode: fileMode, flag: "wx" }); await fs.chmod(tmp, fileMode); await target(root, ref, fs); await fs.rename(tmp, path); }
async function snapshot(root: string, ref: string, fs: Fs): Promise<Snapshot> { const path = await target(root, ref, fs); try { const info = await fs.lstat(path); return { ref, content: await fs.readFile(path, "utf8"), mode: info.mode & 0o777 }; } catch (error) { if (enoent(error)) return { ref, content: null, mode: null }; throw error; } }
function recovery(value: unknown, root: string): Recovery | null { if (!value || typeof value !== "object") return null; const item = value as Partial<Recovery>; if (item.version !== VERSION || item.root !== root || typeof item.project !== "string" || !/^[a-z0-9-]+$/.test(item.project) || typeof item.entry !== "string" || !confined(root, item.entry) || !item.entry.startsWith(`${item.project}/`) || !Array.isArray(item.snapshots)) return null; const expected = [item.entry, `${item.project}/index.md`, "index.md", "skills-inventory.md"]; if (item.snapshots.length !== expected.length) return null; const seen = new Set<string>(), snapshots: Snapshot[] = []; for (const entry of item.snapshots) { if (!entry || typeof entry !== "object") return null; const s = entry as Partial<Snapshot>; if (typeof s.ref !== "string" || !expected.includes(s.ref) || seen.has(s.ref) || (s.content !== null && typeof s.content !== "string") || (s.mode !== null && (!Number.isInteger(s.mode) || s.mode < 0 || s.mode > 0o777))) return null; seen.add(s.ref); snapshots.push({ ref: s.ref, content: s.content, mode: s.mode }); } return seen.size === expected.length ? { version: VERSION, root, project: item.project, entry: item.entry, snapshots } : null; }
async function recover(root: string, fs: Fs): Promise<void> { const canonical = await rootPath(root, fs), marker = await target(canonical, MARKER, fs); let raw: string; try { raw = await fs.readFile(marker, "utf8"); } catch (error) { if (enoent(error)) return; throw error; } let saved: Recovery; try { saved = recovery(JSON.parse(raw), canonical) ?? (() => { throw new Error("invalid recovery marker"); })(); } catch { throw new Error(`Dev-journal recovery marker requires manual repair: ${marker}`); } try { for (const s of saved.snapshots) { const path = await target(canonical, s.ref, fs); if (s.content === null) { try { await fs.unlink(path); } catch (error) { if (!enoent(error)) throw error; } } else await atomic(canonical, s.ref, s.content, s.mode, fs); } await target(canonical, MARKER, fs); await fs.unlink(marker); } catch { throw new Error(`Dev-journal recovery failed; repair marker: ${marker}`); } }
async function confinedFile(root: string, ref: string, fs: Fs): Promise<string> { const lexical = confined(root, ref); if (!lexical) throw new Error("Invalid journal entry reference."); const resolvedRoot = await fs.realpath(root); try { const resolved = await fs.realpath(lexical); if (resolved !== resolve(resolvedRoot, ref) || !under(resolvedRoot, resolved)) throw new Error("escape"); return resolved; } catch { throw new Error("Invalid journal entry reference."); } }
export async function record(root: string, input: RecordInput, fs: Fs = disk): Promise<{ ref: string }> { const problem = validate(input); if (problem) throw new Error(problem); await recover(root, fs); const canonical = await rootPath(root, fs), item = entryFor(input), l1Ref = `${input.project}/index.md`, l0Ref = "index.md", skillsRef = "skills-inventory.md"; const l1 = await read(await target(canonical, l1Ref, fs), fs), l0 = await read(await target(canonical, l0Ref, fs), fs), skills = await read(await target(canonical, skillsRef, fs), fs); const l1Next = `${l1.trimEnd()}${l1.trim() ? "\n" : ""}${item.l1}\n`; const l0Line = `${input.project} — ${input.impact} {${input.skills[0] ?? "general"}} · ${l1Next.trim().split("\n").length} entries · last ${item.ref.slice(input.project.length + 1, input.project.length + 11)} · @${input.company} · notable: [[${input.project}/index|${input.title}]]`; const l0Next = l0.includes(`${input.project} —`) ? l0.replace(new RegExp(`^${input.project} —.*$`, "m"), l0Line) : `${l0.trimEnd()}\n${l0.trim() ? "" : "## " + input.company + "\n"}${l0Line}\n`; let skillsNext = skills; for (const skill of input.skills) { const line = `- **${skill}** — level: touched · [[${item.ref.slice(0, -3)}|${input.title}]]`; skillsNext = skillsNext.includes(`**${skill}**`) ? skillsNext.replace(new RegExp(`^(- \\*\\*${escapeRegex(skill)}\\*\\*.*)$`, "m"), `$1, [[${item.ref.slice(0, -3)}|${input.title}]]`) : `${skillsNext.trimEnd()}\n${line}\n`; }
  const snapshots = await Promise.all([snapshot(canonical, item.ref, fs), snapshot(canonical, l1Ref, fs), snapshot(canonical, l0Ref, fs), snapshot(canonical, skillsRef, fs)]); await atomic(canonical, MARKER, JSON.stringify({ version: VERSION, root: canonical, project: input.project, entry: item.ref, snapshots }), PRIVATE, fs); const writes = [{ ref: item.ref, value: item.l2, mode: snapshots[0].mode }, { ref: l1Ref, value: l1Next, mode: snapshots[1].mode }, { ref: l0Ref, value: l0Next, mode: snapshots[2].mode }, { ref: skillsRef, value: skillsNext, mode: snapshots[3].mode }]; try { for (const write of writes) await atomic(canonical, write.ref, write.value, write.mode, fs); await target(canonical, MARKER, fs); await fs.unlink(resolve(canonical, MARKER)); } catch (error) { try { await recover(canonical, fs); } catch (rollback) { throw rollback; } throw error; } return { ref: item.ref }; }
export async function recall(root: string, project: string, query?: string, fs: Fs = disk): Promise<string> { await recover(root, fs); const l1 = await read(resolve(root, project, "index.md"), fs); const q = (query ?? "").toLowerCase(); const line = l1.split("\n").find((x) => !q || x.toLowerCase().includes(q)); return text(line ? `Precedent: ${line}` : "No journal hit."); }
export async function details(root: string, ref: string, fs: Fs = disk): Promise<string> { await recover(root, fs); return text(await read(await confinedFile(root, ref, fs), fs), MAX_DETAILS_BYTES); }
function shellWords(command: string): string[] | null { if (/[;&|\r\n`$<>\\]/.test(command)) return null; const words: string[] = []; let word = "", quote = ""; for (let i = 0; i < command.length; i++) { const char = command[i]; if (quote) { if (char === quote) quote = ""; else word += char; } else if (char === "\"" || char === "'") quote = char; else if (/\s/.test(char)) { if (word) { words.push(word); word = ""; } } else word += char; } return quote ? null : word ? [...words, word] : words; }
export function isSuccessfulBashResult(result: unknown): boolean { if (!result || typeof result !== "object") return false; const value = result as { isError?: unknown; exitCode?: unknown; cancelled?: unknown }; if (value.isError === false) return true; return value.exitCode === 0 && value.cancelled === false; }
export function hasCommitEvidence(command: unknown, output: unknown, result: unknown): boolean { if (typeof command !== "string" || typeof output !== "string" || !isSuccessfulBashResult(result)) return false; const words = shellWords(command); if (!words || words[0] !== "git") return false; const flags = new Set(["-p", "-P", "--paginate", "--no-pager", "--no-replace-objects", "--bare"]), values = new Set(["-C", "-c", "--git-dir", "--work-tree", "--namespace", "--config-env", "--super-prefix"]); let index = 1; while (words[index] !== "commit") { const option = words[index++]; if (!option || (!(flags.has(option)) && !(values.has(option)) && !/^(--git-dir|--work-tree|--namespace|--config-env|--super-prefix)=.+$/.test(option))) return false; if (values.has(option) && (!words[index] || words[index++] === "commit")) return false; } return !words.slice(index + 1).some((word) => word === "--dry-run" || word.startsWith("--dry-run=")) && /^\[(?:.+ )?(?:\(root-commit\) )?[0-9a-f]{7,40}\] [^\r\n]+$/mi.test(output); }
