name: Daily update

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v20
      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update inputs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: scripts/daily-update.sh inputs

  plugins:
    if: always()
    needs: inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v20
      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update plugins
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: scripts/daily-update.sh plugins
